import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { Container } from "../../../design-system/primitives/Container.jsx"
import { PaymentStatusBadge } from "../../flights/components/PaymentStatusBadge.jsx"
import { myTripsDataSource } from "../../../services/myTripsDataSource.js"

function EmptyTrips() { return <section className="trips-empty" data-state="empty"><span aria-hidden="true">✈</span><h2>لا توجد حجوزات بعد</h2><p>ستظهر حجوزاتك هنا بعد بدء حجز.</p><Link to="/flights">استكشف الرحلات</Link></section> }
function LoadingTrips() { return <section className="trips-empty" role="status" aria-live="polite" data-state="loading"><h2>جارٍ تحميل حجوزاتك</h2><p>يتم الآن طلب بيانات حسابك الآمنة.</p></section> }
function ErrorTrips({ retry }) { return <section className="trips-empty trips-invalid" role="alert" data-state="error"><h2>تعذر عرض الحجوزات</h2><p>تحقق من تسجيل الدخول ثم أعد المحاولة. لم تُعرض بيانات بديلة.</p><button type="button" onClick={retry}>إعادة المحاولة</button></section> }

export function MyTripsPage({ dataSource = myTripsDataSource }) {
  const [request, setRequest] = useState({ status: "loading", trips: [] })
  const [ticketDetails, setTicketDetails] = useState({})
  const [attempt, setAttempt] = useState(0)
  useEffect(() => { let active = true; setRequest({ status: "loading", trips: [] }); dataSource.load().then(trips => { if (active) setRequest({ status: "success", trips }) }).catch(() => { if (active) setRequest({ status: "error", trips: [] }) }); return () => { active = false } }, [dataSource, attempt])
  return <div className="my-trips-page" dir="rtl" data-view="my-trips" data-layout="responsive-desktop-mobile" data-authority="authenticated-rpc"><Container>
    <header className="trips-heading"><div><span>الحساب</span><h1>حجوزاتي</h1><p>تابع حالة الحجز والدفع كلٌ على حدة.</p></div><span className="presentation-fixture-label">بيانات حسابك المحمية</span></header>
    {request.status === "loading" ? <LoadingTrips /> : request.status === "error" ? <ErrorTrips retry={() => setAttempt(value => value + 1)} /> : request.trips.length === 0 ? <EmptyTrips /> : <div className="trip-list" aria-label="قائمة حجوزات الرحلات">{request.trips.map(trip => <article className="trip-card" key={trip.key} data-booking-state={trip.bookingState} data-ticketing-state={trip.ticketingState}><div className="trip-card__top"><div className="payment-status-badges" aria-label="حالة الدفع وحالة الحجز"><PaymentStatusBadge domain="payment" status={trip.paymentState}/><PaymentStatusBadge domain="booking" status={trip.bookingState}/></div><span className="trip-reference latin-text" dir="ltr">{trip.reference}</span></div><div className="trip-card__body"><div><h2>حجز رحلة</h2><p>أُنشئ في <bdi className="latin-text">{new Intl.DateTimeFormat("ar", { dateStyle: "medium" }).format(new Date(trip.createdAt))}</bdi></p><p role="status">{trip.ticketingLabel}</p><small><bdi className="latin-text">{trip.amount ?? "—"} {trip.currency}</bdi> · طريقة الدفع: <bdi className="latin-text">{trip.paymentMethod}</bdi></small>{trip.canViewTicketDetails && <button type="button" onClick={() => { setTicketDetails(current => ({ ...current, [trip.reference]: { status: "loading", rows: [] } })); dataSource.loadTicketDetails(trip.reference).then(rows => setTicketDetails(current => ({ ...current, [trip.reference]: { status: "success", rows } }))).catch(() => setTicketDetails(current => ({ ...current, [trip.reference]: { status: "error", rows: [] } }))) }}>عرض بيانات التذكرة</button>}{ticketDetails[trip.reference]?.status === "loading" && <small role="status">جارٍ تحميل بيانات التذكرة</small>}{ticketDetails[trip.reference]?.status === "error" && <small role="alert">تعذر تحميل بيانات التذكرة</small>}{ticketDetails[trip.reference]?.status === "success" && <ul>{ticketDetails[trip.reference].rows.map(ticket => <li key={ticket.ticketNumber}><bdi className="latin-text">{ticket.ticketNumber}</bdi> · {ticket.artifactAvailability === "AVAILABLE" ? "المستند متاح عبر خدمة التنزيل الموثوقة" : "بيانات التذكرة متاحة، ولا يوجد مستند قابل للتنزيل"}</li>)}</ul>}</div><span className="trip-card__link trip-card__link--disabled" aria-disabled="true">{trip.canDownloadTicket ? "التنزيل يتطلب خدمة المستندات الموثوقة" : "تحميل التذكرة غير متاح"}</span></div></article>)}</div>}
  </Container></div>
}
