import { useState } from "react"
import { Container } from "../../../design-system/primitives/Container.jsx"
import { resolveRoom } from "../data/hotelCanonicalFixtures.js"
import { HotelSandboxNotice } from "./HotelSandboxNotice.jsx"

const BOUNDARY_COPY = "هذه نهاية العرض. لم يتم إنشاء حجز أو عملية دفع أو حجز غرفة مؤقت."

export function GuestDetails({ roomKey, onBack, onReview }) {
  const room = resolveRoom(roomKey)
  const [boundary, setBoundary] = useState("")
  const review = () => onReview ? onReview(room.canonicalRateId) : setBoundary(BOUNDARY_COPY)
  return <div className="hotels-page hotel-guest-page hotels-v2" data-view="guest" data-checkout-boundary="presentation-only" data-pii-persistence="none" data-layout="responsive-desktop-mobile"><Container><button className="hotel-back hotels-v2__back" type="button" onClick={onBack}>← العودة إلى اختيار الغرفة</button><HotelSandboxNotice/><header className="guest-heading hotels-v2__heading"><h1>بيانات الضيف</h1><p>أدخل بيانات الشخص الرئيسي الذي سيقيم في الفندق</p></header><ol className="hotel-steps hotels-v2__steps"><li>1 اختيار الغرفة</li><li aria-current="step">2 بيانات الضيف</li><li>3 الدفع</li></ol><div className="guest-layout hotels-v2__layout"><main><section className="guest-form hotels-v2__panel"><h2>الضيف الرئيسي</h2><p>استخدم الاسم كما يظهر في وثيقة الهوية أو جواز السفر.</p><div className="guest-fields hotels-v2__fields"><label>الاسم الأول <input defaultValue="MOHAMED" dir="ltr" autoComplete="off"/></label><label>اسم العائلة <input defaultValue="AHMED" dir="ltr" autoComplete="off"/></label><label>رقم الهاتف <input defaultValue="+971 50 123 4567" dir="ltr" autoComplete="off"/></label><label>البريد الإلكتروني <input defaultValue="name@example.com" dir="ltr" autoComplete="off"/></label></div></section><section className="guest-note hotels-v2__privacy v2-no-motion"><strong>بيانات التواصل تُستخدم لهذه الشاشة فقط في H1.</strong><span>لا تُكتب في الرابط أو التخزين أو التحليلات أو السجلات، ولا يُنشأ حجز أو دفع.</span></section></main><aside className="stay-summary hotels-v2__summary"><h2>ملخص الإقامة</h2><strong>فندق النخلة دبي</strong><p>15–18 سبتمبر · 3 ليالٍ</p><p>{room.name.split(" · ")[0]} · {room.meal}</p><strong className="selected-price latin-text hotels-v2__summary-price" dir="ltr">{room.price} AED</strong><hr/><p>{room.tax}</p><button className="v2-button v2-button--primary hotels-v2__cta" type="button" onClick={review}>مراجعة الحجز</button>{boundary && <p role="status" aria-live="polite" className="checkout-boundary hotels-v2__boundary v2-no-motion">{boundary}</p>}</aside></div></Container><div className="guest-mobile-summary hotels-v2__mobile-bar"><strong className="latin-text" dir="ltr">{room.price} AED</strong><button type="button" onClick={review}>مراجعة</button></div></div>
}
