import { useState } from "react"
import { Container } from "../../../design-system/primitives/Container.jsx"
import { PALM_ROOMS } from "../data/hotelCanonicalFixtures.js"
import { HotelSandboxNotice } from "./HotelSandboxNotice.jsx"

export function RoomSelection({ initialRoomKey, onBack, onGuest }) {
  const [selectedKey, setSelectedKey] = useState(PALM_ROOMS.some(room => room.canonicalRateId === initialRoomKey) ? initialRoomKey : PALM_ROOMS[0].canonicalRateId)
  const room = PALM_ROOMS.find(item => item.canonicalRateId === selectedKey)
  return <div className="hotels-page hotel-room-page hotels-v2" data-view="rooms" data-hotel-key="palm-dubai" data-canonical-hotel-id="hjz_htl_palm_dubai" data-layout="responsive-desktop-mobile"><Container><button className="hotel-back hotels-v2__back" type="button" onClick={onBack}>← العودة إلى نتائج الفنادق</button><HotelSandboxNotice/><section className="hotel-summary hotels-v2__stay"><div><h1>فندق النخلة دبي</h1><div className="hotel-stars">★★★★★</div><p>دبي · نخلة جميرا</p></div><div><strong>15–18 سبتمبر</strong><p>3 ليالٍ · 2 بالغين · غرفة واحدة</p></div><div className="hotel-contract-note"><strong>قارن الغرف حسب السعر والوجبات وشروط الإلغاء والضرائب.</strong><span>السعر النهائي لكل خيار يظهر قبل المتابعة؛ لا نعرض بيانات المورّد.</span></div></section><header className="room-heading hotels-v2__heading"><h1>اختر الغرفة والسعر</h1><p>جميع الخيارات أدناه لنفس الفندق والإقامة المحددة.</p></header><div className="rooms-layout hotels-v2__layout"><main><div className="room-list">{PALM_ROOMS.map(item => <article key={item.canonicalRateId} className={`room-option hotels-v2__room${selectedKey === item.canonicalRateId ? " is-selected" : ""}`} data-room-key={item.key} data-canonical-rate-id={item.canonicalRateId}><div><strong>{item.name}</strong><small>{item.meal}</small></div><div className="room-terms"><span>{item.tax}</span><span>{item.cancellation.label}</span></div><div><strong className="latin-text hotels-v2__price-value" dir="ltr">{item.price} AED</strong><button className="v2-button v2-button--secondary hotels-v2__room-action" type="button" onClick={() => setSelectedKey(item.canonicalRateId)} aria-pressed={selectedKey === item.canonicalRateId}>{selectedKey === item.canonicalRateId ? "محدد" : "اختيار"}</button></div></article>)}</div><section className="room-notes hotels-v2__notes"><h2>ملاحظات السعر</h2><p>• الأسعار تخص 3 ليالٍ للإقامة المحددة.</p><p>• أي رسوم تُدفع في الفندق تظهر منفصلة ولا تُدمج في مبلغ حاجز.</p><p>• شروط الإلغاء تُعرض حسب بيانات الخيار المختار.</p></section></main><aside className="selected-room hotels-v2__summary"><h2>الخيار المحدد</h2><strong>{room.name.split(" · ")[0]}</strong><p>{room.meal} · 3 ليالٍ</p><strong className="selected-price latin-text hotels-v2__summary-price" dir="ltr">{room.price} AED</strong><hr/><p>{room.tax}</p><p>شروط الإلغاء: {room.cancellation.label}</p><button className="v2-button v2-button--primary hotels-v2__cta" type="button" onClick={() => onGuest(room.canonicalRateId)}>متابعة لبيانات الضيف</button></aside></div></Container><div className="room-mobile-summary hotels-v2__mobile-bar"><strong className="latin-text" dir="ltr">{room.price} AED</strong><button type="button" onClick={() => onGuest(room.canonicalRateId)}>متابعة</button></div></div>
}
